"""Generates deployment artefacts so that they stay consistent with common/topology.py:

    python -m deploy.generate

  deploy/topology.json            topology with DNS names (used by the containers)
  docker-compose.yml              fault-tolerant system (2 replicas per tier, replicated DB volume, Prometheus, Grafana)
  docker-compose.baseline.yml     baseline system (single instances, no restart policy)
  deploy/k8s/*.yaml               Kubernetes manifests (StatefulSets x2 replicas, probes, anti-affinity, PDB, rolling
                                  update, Prometheus + Grafana) and kustomization.yaml (`kubectl apply -k deploy/k8s`)
  deploy/kind/*                   local 3-node cluster: kind config + overlay (`kubectl apply -k deploy/kind`)
  deploy/monitoring/prometheus.yml, alerts.yml, grafana provisioning + dashboard
"""
import hashlib
import json
import os
from dataclasses import asdict

from common import topology

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "deploy")
CONTAINER_PORT = 8000
PROMETHEUS_IMAGE = "prom/prometheus:v3.15.0"
GRAFANA_IMAGE = "grafana/grafana:13.2.3"
NODEPORT = {"gateway": 30080, "prometheus": 30090, "grafana": 30300}   # fixed so kind can map them to localhost
DS = {"type": "prometheus", "uid": "prometheus"}

# alert rules = automated failure *detection* on top of the metrics (shown in Prometheus -> Alerts)
ALERTS = """groups:
  - name: university-is
    rules:
      - alert: InstanceDown              # min_over_time: a crash + restart shorter than one scrape is still caught
        expr: min_over_time(target_up[10s]) == 0
        labels: {severity: warning}
        annotations:
          summary: "{{ $labels.instance }} failed its health check in the last 10 s (masked if a replica is up)"
      - alert: ServiceTierDown
        expr: sum by (service) (target_up) == 0
        labels: {severity: critical}
        annotations:
          summary: "no healthy replica of {{ $labels.service }}: user-visible outage"
      - alert: GatewayErrorRateHigh
        expr: (sum(rate(http_requests_total{service="gateway",code=~"5.."}[30s])) or vector(0)) / sum(rate(http_requests_total{service="gateway"}[30s])) > 0.05
        for: 10s
        labels: {severity: critical}
        annotations:
          summary: "more than 5% of user requests fail"
      - alert: DatabasePrimaryUnavailable
        expr: min(db_primary_available) == 0
        for: 2s
        labels: {severity: warning}
        annotations:
          summary: "primary database unreachable: reads served by the replica, writes journaled (HTTP 202)"
      - alert: CircuitBreakerOpen
        expr: max(gateway_circuit_open) > 0 or max(db_circuit_open) > 0
        labels: {severity: info}
        annotations:
          summary: "a circuit breaker is open (fail-fast in progress)"
"""


def block(text, indent):
    """Indent a multi-line string for use as a YAML block scalar."""
    pad = " " * indent
    return "\n".join(pad + line if line else line for line in text.rstrip("\n").split("\n"))


def docker_instances(mode):
    out = []
    for i in topology.build(mode):
        i.port, i.host = CONTAINER_PORT, i.id
        out.append(i)
    return out


def app_of(inst, mode):
    return "common.monitor" if inst.service == "monitor" else f"{'ft' if mode == 'ft' else 'baseline'}.{inst.service}"


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def compose(mode):
    inst = docker_instances(mode)
    write(os.path.join(D, "topology.json" if mode == "ft" else "topology.baseline.json"),
          json.dumps({"mode": mode, "instances": [asdict(i) for i in inst]}, indent=1))
    topo_src = "/app/deploy/topology.json" if mode == "ft" else "/app/deploy/topology.baseline.json"
    restart = "unless-stopped" if mode == "ft" else '"no"'
    L = ["# generated by deploy/generate.py - do not edit by hand",
         "x-common: &common", "  image: univ-is:latest", f"  restart: {restart}",
         "  environment: &env", "    DATA_DIR: /data", "    TOPOLOGY_FILE: /data/topology.json",
         "  volumes: [\"data:/data\"]", "  depends_on:", "    init: {condition: service_completed_successfully}", "",
         "services:", "  init:", "    image: univ-is:latest", "    build: .",
         f"    command: [\"python\", \"-m\", \"deploy.init_data\", \"{mode}\"]",
         f"    environment: {{DATA_DIR: /data, TOPOLOGY_SRC: {topo_src}}}",
         "    volumes: [\"data:/data\"]", "    restart: \"no\""]
    for i in inst:
        health = "/health/ready" if (mode == "ft" and i.service != "monitor") else "/health/live"
        L += [f"  {i.id}:", "    <<: *common", f"    container_name: {i.id}",
              "    environment:", "      <<: *env", f"      APP: {app_of(i, mode)}", f"      INSTANCE_ID: {i.id}",
              f"      NODE: {i.node}",
              "    healthcheck:",
              f"      test: [\"CMD\", \"python\", \"-c\", \"import urllib.request as u; u.urlopen('http://localhost:{CONTAINER_PORT}{health}', timeout=2)\"]",
              "      interval: 2s", "      timeout: 2s", "      retries: 2", "      start_period: 3s"]
        if i.service == "gateway":
            n = int(i.id.split("-")[1])
            L += ["    ports:", f"      - \"{8000 + n - 1}:{CONTAINER_PORT}\""]
        if i.service == "monitor":
            L += ["    ports:", f"      - \"8200:{CONTAINER_PORT}\""]
    if mode == "ft":
        L += ["  prometheus:", f"    image: {PROMETHEUS_IMAGE}", "    container_name: prometheus",
              "    restart: unless-stopped",
              "    volumes:",
              "      - ./deploy/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro",
              "      - ./deploy/monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro",
              "    healthcheck:",
              "      test: [\"CMD\", \"wget\", \"-qO-\", \"http://localhost:9090/-/ready\"]",
              "      interval: 5s", "      timeout: 3s", "      retries: 5",
              "    ports: [\"9090:9090\"]",
              "  grafana:", f"    image: {GRAFANA_IMAGE}", "    container_name: grafana", "    restart: unless-stopped",
              "    volumes:", "      - ./deploy/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro",
              "      - ./deploy/monitoring/grafana/dashboards:/etc/grafana/dashboards:ro",
              "    environment:", "      GF_AUTH_ANONYMOUS_ENABLED: \"true\"", "      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin",
              "      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/dashboards/dependability.json",
              "    healthcheck:",
              "      test: [\"CMD\", \"wget\", \"-qO-\", \"http://localhost:3000/api/health\"]",
              "      interval: 5s", "      timeout: 3s", "      retries: 10",
              "    ports: [\"3000:3000\"]", "    depends_on: [prometheus]"]
    L += ["", "volumes:", "  data:"]
    write(os.path.join(ROOT, "docker-compose.yml" if mode == "ft" else "docker-compose.baseline.yml"), "\n".join(L) + "\n")
    return inst


PROM_GLOBAL = """global:
  scrape_interval: 2s
  evaluation_interval: 2s
rule_files: [/etc/prometheus/alerts.yml]
"""
GRAFANA_DATASOURCE = """apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData: {timeInterval: 2s}
"""
GRAFANA_PROVIDER = """apiVersion: 1
providers:
  - name: university-is
    type: file
    allowUiUpdates: true
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/dashboards
"""


def dashboard():
    R = "15s"   # rate window: ~7 scrapes at 2 s

    def q(expr, legend):
        return {"expr": expr, "legendFormat": legend, "datasource": DS}

    def panel(pid, kind, title, targets, x, y, w, h, unit=None, desc=None, red_from=None, mappings=None,
              overrides=(), **opts):
        p = {"id": pid, "type": kind, "title": title, "datasource": DS, "gridPos": {"x": x, "y": y, "w": w, "h": h},
             "targets": [{**t, "refId": chr(65 + k)} for k, t in enumerate(targets)],
             "fieldConfig": {"defaults": {"mappings": mappings or []}, "overrides": list(overrides)}, "options": opts}
        if desc:
            p["description"] = desc
        if unit:
            p["fieldConfig"]["defaults"]["unit"] = unit
        if red_from is not None:
            p["fieldConfig"]["defaults"]["thresholds"] = {"mode": "absolute", "steps": [
                {"color": "green", "value": None}, {"color": "red", "value": red_from}]}
        return p

    gw_ok = (f'1 - ((sum(rate(http_requests_total{{service="gateway",code=~"5.."}}[{R}])) or vector(0))'
             f' / sum(rate(http_requests_total{{service="gateway"}}[{R}])))')
    panels = [
        panel(1, "stat", "Instances healthy", [q("sum(target_up)", "healthy")], 0, 0, 6, 4,
              desc="Replicas passing the monitor's readiness check (0.5 s polling)."),
        panel(2, "stat", "Instances down", [q("count(target_up) - sum(target_up)", "down")], 6, 0, 6, 4, red_from=1),
        panel(3, "stat", f"User-visible success ratio ({R})", [q(gw_ok, "success")], 12, 0, 6, 4, unit="percentunit",
              desc="Share of requests answered by the gateways without a 5xx (= measured availability)."),
        panel(4, "stat", "Writes queued in journal", [q("max(db_journal_pending) or vector(0)", "pending")], 18, 0, 6, 4,
              red_from=1, desc="Store-and-forward outbox: writes accepted with HTTP 202 while the primary DB is down."),
        panel(5, "state-timeline", "Health checks per instance (monitor, 0.5 s polling)", [q("target_up", "{{instance}}")],
              0, 4, 24, 9, showValue="never", mergeValues=True, mappings=[{"type": "value", "options": {
                  "1": {"text": "UP", "color": "green", "index": 0}, "0": {"text": "DOWN", "color": "red", "index": 1}}}]),
        panel(6, "timeseries", "Request rate by instance (req/s)",
              [q(f"sum by (instance) (rate(http_requests_total[{R}]))", "{{instance}}")], 0, 13, 12, 8, unit="reqps"),
        panel(7, "timeseries", "Failed requests (5xx/s) by instance",
              [q(f'sum(rate(http_requests_total{{code=~"5.."}}[{R}])) or vector(0)', "all instances"),
               q(f'sum by (instance) (rate(http_requests_total{{code=~"5.."}}[{R}]))', "{{instance}}")], 12, 13, 12, 8,
              unit="reqps"),
        panel(8, "timeseries", "Mean latency by instance",
              [q(f"sum by (instance) (rate(http_request_duration_seconds_sum[{R}])) / "
                 f"sum by (instance) (rate(http_request_duration_seconds_count[{R}]))", "{{instance}}")],
              0, 21, 12, 8, unit="s"),
        panel(9, "timeseries", "Faults masked by the gateway (events/s)",
              [q(f"sum(rate(gateway_{k}_total[{R}]))", label) for k, label in
               [("retries", "retry on another replica"), ("stale", "stale-cache answer (degraded)"),
                ("shed", "load shed (priority)"), ("failed", "not masked -> 503")]], 12, 21, 12, 8, unit="ops",
              desc="Retries with backoff, graceful degradation and load shedding as they happen."),
        panel(10, "timeseries", "Circuit breakers open",
              [q("(sum(gateway_circuit_open) + sum(db_circuit_open)) or vector(0)", "open breakers (total)"),
               q("sum by (target) (gateway_circuit_open) > 0", "gateway -> {{target}}"),
               q("max by (instance) (db_circuit_open) > 0", "{{instance}} -> primary DB")], 0, 29, 12, 8),
        panel(11, "timeseries", "Database: primary availability, replica failover, journal",
              [q("min(db_primary_available)", "primary available (min over services)"),
               q(f"sum(rate(db_replica_reads_total[{R}]))", "reads served by replica /s"),
               q("max(db_journal_pending)", "journal pending"),
               q(f"sum(rate(db_journal_replayed_total[{R}]))", "journal replayed /s")], 12, 29, 12, 8,
              overrides=[{"matcher": {"id": "byName", "options": "primary available (min over services)"},
                          "properties": [{"id": "custom.axisPlacement", "value": "right"}, {"id": "min", "value": 0},
                                         {"id": "max", "value": 1}, {"id": "custom.lineWidth", "value": 3}]}]),
    ]
    return {"title": "University IS - dependability", "uid": "univ-is", "schemaVersion": 39, "refresh": "5s",
            "time": {"from": "now-10m", "to": "now"}, "tags": ["fault-tolerance"], "panels": panels}


def prometheus_static(inst):
    """docker-compose: fixed container names; instance label = container name (port stripped)."""
    targets = ", ".join(f"'{i.id}:{CONTAINER_PORT}'" for i in inst)
    return PROM_GLOBAL + f"""scrape_configs:
  - job_name: university-is
    honor_labels: true            # keep the service/instance labels exported by the application
    static_configs:
      - targets: [{targets}]
    relabel_configs:
      - source_labels: [__address__]
        regex: '(([a-z]+)-[0-9]+):[0-9]+'
        replacement: '$1'
        target_label: instance
      - source_labels: [__address__]
        regex: '(([a-z]+)-[0-9]+):[0-9]+'
        replacement: '$2'
        target_label: service
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
"""


def prometheus_k8s(ns):
    """Kubernetes: pods are discovered through the API (pods annotated prometheus.io/scrape=true), so replicas that
    are rescheduled or scaled are picked up automatically."""
    return PROM_GLOBAL + f"""scrape_configs:
  - job_name: university-is
    honor_labels: true
    kubernetes_sd_configs:
      - role: pod
        namespaces: {{names: [{ns}]}}
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_kubernetes_pod_phase]
        regex: Running
        action: keep
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: '(.+);(.+)'
        replacement: '$1:$2'
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: k8s_node
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
"""


def monitoring(inst):
    M = os.path.join(D, "monitoring")
    write(os.path.join(M, "prometheus.yml"), prometheus_static(inst))
    write(os.path.join(M, "alerts.yml"), ALERTS)
    write(os.path.join(M, "grafana", "provisioning", "datasources", "prom.yml"), GRAFANA_DATASOURCE)
    write(os.path.join(M, "grafana", "provisioning", "dashboards", "dash.yml"), GRAFANA_PROVIDER)
    write(os.path.join(M, "grafana", "dashboards", "dependability.json"), json.dumps(dashboard(), indent=1))


def k8s(inst):
    K = os.path.join(D, "k8s")
    ns = "univ"
    write(os.path.join(K, "00-namespace.yaml"), f"apiVersion: v1\nkind: Namespace\nmetadata:\n  name: {ns}\n")
    topo = {"mode": "ft", "instances": []}
    groups = {}
    for i in inst:
        if i.service == "monitor":
            groups.setdefault("monitor", []).append(i)
            continue
        groups.setdefault(i.service, []).append(i)
    # pods of a StatefulSet are <name>-0, <name>-1; the headless service gives each a stable DNS name
    for svc, items in groups.items():
        for k, i in enumerate(items):
            pod = f"{svc}-{k}"
            topo["instances"].append({"service": svc, "id": pod, "node": "A" if k == 0 else "B", "port": CONTAINER_PORT,
                                      "host": f"{pod}.{svc}"})
    cm = json.dumps(topo, indent=2).replace("\n", "\n    ")
    write(os.path.join(K, "01-config-storage.yaml"),
          f"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: topology\n  namespace: {ns}\ndata:\n  topology.json: |\n    {cm}\n---\n"
          f"# NOTE: SQLite needs a POSIX volume shared by all pods (RWX: NFS, CephFS, Azure Files, EFS ...). No\n"
          f"# storageClassName here = the cluster default; deploy/kind/ patches in a shared hostPath volume for local\n"
          f"# clusters. For production use PostgreSQL with streaming replication instead (see report, section 11).\n"
          f"apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: data\n  namespace: {ns}\nspec:\n  accessModes: [ReadWriteMany]\n"
          f"  resources:\n    requests:\n      storage: 1Gi\n---\n"
          f"apiVersion: batch/v1\nkind: Job\nmetadata:\n  name: init-data\n  namespace: {ns}\nspec:\n  template:\n    spec:\n"
          f"      restartPolicy: OnFailure\n      containers:\n        - name: init\n          image: univ-is:latest\n          imagePullPolicy: IfNotPresent\n"
          f"          command: [\"python\", \"-m\", \"deploy.init_data\", \"ft\"]\n          env:\n            - {{name: DATA_DIR, value: /data}}\n"
          f"            - {{name: TOPOLOGY_SRC, value: /config/topology.json}}\n          volumeMounts:\n"
          f"            - {{name: data, mountPath: /data}}\n            - {{name: topo, mountPath: /config}}\n      volumes:\n"
          f"        - name: data\n          persistentVolumeClaim: {{claimName: data}}\n        - name: topo\n          configMap: {{name: topology}}\n")
    for svc, items in groups.items():
        app = "common.monitor" if svc == "monitor" else f"ft.{svc}"
        replicas = len(items)
        probe_ready = "/health/live" if svc == "monitor" else "/health/ready"
        y = f"""apiVersion: v1
kind: Service
metadata:
  name: {svc}
  namespace: {ns}
spec:
  clusterIP: None            # headless: stable per-pod DNS names (<pod>.{svc})
  selector: {{app: {svc}}}
  ports: [{{port: {CONTAINER_PORT}}}]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {svc}
  namespace: {ns}
spec:
  serviceName: {svc}
  replicas: {replicas}                       # service replication
  podManagementPolicy: Parallel
  updateStrategy: {{type: RollingUpdate}}    # rolling updates, one replica at a time
  selector:
    matchLabels: {{app: {svc}}}
  template:
    metadata:
      labels: {{app: {svc}}}
      annotations:                         # picked up by Prometheus' Kubernetes service discovery
        prometheus.io/scrape: "true"
        prometheus.io/port: "{CONTAINER_PORT}"
    spec:
      initContainers:                      # never start on a half-created database (init-data Job writes the marker last)
        - name: wait-for-data
          image: univ-is:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until [ -f /data/.initialized ]; do echo waiting for init-data; sleep 1; done"]
          volumeMounts:
            - {{name: data, mountPath: /data}}
      affinity:
        podAntiAffinity:                   # replicas of one tier land on different nodes
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector: {{matchLabels: {{app: {svc}}}}}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: {svc}
          image: univ-is:latest
          imagePullPolicy: IfNotPresent
          env:
            - {{name: APP, value: {app}}}
            - {{name: DATA_DIR, value: /data}}
            - {{name: TOPOLOGY_FILE, value: /config/topology.json}}
            - {{name: INSTANCE_ID, valueFrom: {{fieldRef: {{fieldPath: metadata.name}}}}}}
            - {{name: NODE, valueFrom: {{fieldRef: {{fieldPath: spec.nodeName}}}}}}
          ports: [{{containerPort: {CONTAINER_PORT}}}]
          readinessProbe:                  # health check -> removed from service endpoints when failing
            httpGet: {{path: {probe_ready}, port: {CONTAINER_PORT}}}
            periodSeconds: 2
            failureThreshold: 2
          livenessProbe:                   # self-healing: kubelet restarts a hung process
            httpGet: {{path: /health/live, port: {CONTAINER_PORT}}}
            periodSeconds: 3
            failureThreshold: 3
          resources:
            requests: {{cpu: 100m, memory: 128Mi}}
            limits: {{cpu: 500m, memory: 256Mi}}
          volumeMounts:
            - {{name: data, mountPath: /data}}
            - {{name: topo, mountPath: /config}}
      volumes:
        - name: data
          persistentVolumeClaim: {{claimName: data}}
        - name: topo
          configMap: {{name: topology}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget                  # node drains / upgrades can never remove the last replica
metadata:
  name: {svc}
  namespace: {ns}
spec:
  minAvailable: {max(0, replicas - 1)}
  selector:
    matchLabels: {{app: {svc}}}
"""
        if svc == "gateway":
            y += f"""---
apiVersion: v1
kind: Service                              # load balancer in front of the two gateways (client entry point)
metadata:
  name: gateway-lb
  namespace: {ns}
spec:
  type: LoadBalancer                       # gets an external IP on a cloud; the fixed nodePort works everywhere
  selector: {{app: gateway}}
  ports: [{{port: 80, targetPort: {CONTAINER_PORT}, nodePort: {NODEPORT["gateway"]}}}]
"""
        write(os.path.join(K, f"10-{svc}.yaml"), y)
    write(os.path.join(K, "20-monitoring.yaml"), k8s_monitoring(ns))
    files = ["00-namespace.yaml", "01-config-storage.yaml"] + [f"10-{s}.yaml" for s in groups] + ["20-monitoring.yaml"]
    write(os.path.join(K, "kustomization.yaml"),
          "# kubectl apply -k deploy/k8s     (generated by deploy/generate.py)\n"
          "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n"
          + "".join(f"  - {f}\n" for f in files))


def k8s_monitoring(ns):
    dash = json.dumps(dashboard(), indent=1)
    return f"""# Prometheus + Grafana inside the cluster (generated by deploy/generate.py)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {ns}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role                                 # least privilege: discovery of pods in this namespace only
metadata:
  name: prometheus
  namespace: {ns}
rules:
  - apiGroups: [""]
    resources: [pods, services, endpoints]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: {ns}
roleRef: {{apiGroup: rbac.authorization.k8s.io, kind: Role, name: prometheus}}
subjects: [{{kind: ServiceAccount, name: prometheus, namespace: {ns}}}]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {ns}
data:
  prometheus.yml: |
{block(prometheus_k8s(ns), 4)}
  alerts.yml: |
{block(ALERTS, 4)}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {ns}
  labels: {{app: prometheus, tier: monitoring}}
spec:
  replicas: 1
  selector:
    matchLabels: {{app: prometheus}}
  template:
    metadata:
      labels: {{app: prometheus, tier: monitoring}}
      annotations:
        checksum/config: "{hashlib.sha256((prometheus_k8s(ns) + ALERTS).encode()).hexdigest()[:16]}"   # config change -> rolling restart
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: {PROMETHEUS_IMAGE}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=2d
            - --web.enable-lifecycle
          ports: [{{containerPort: 9090}}]
          readinessProbe:
            httpGet: {{path: /-/ready, port: 9090}}
            periodSeconds: 5
          livenessProbe:
            httpGet: {{path: /-/healthy, port: 9090}}
            periodSeconds: 10
          resources:
            requests: {{cpu: 100m, memory: 256Mi}}
            limits: {{cpu: "1", memory: 1Gi}}
          volumeMounts:
            - {{name: config, mountPath: /etc/prometheus}}
            - {{name: tsdb, mountPath: /prometheus}}
      volumes:
        - name: config
          configMap: {{name: prometheus-config}}
        - name: tsdb
          emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {ns}
spec:
  type: NodePort
  selector: {{app: prometheus}}
  ports: [{{port: 9090, targetPort: 9090, nodePort: {NODEPORT["prometheus"]}}}]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {ns}
data:
  datasource.yml: |
{block(GRAFANA_DATASOURCE, 4)}
  dashboards.yml: |
{block(GRAFANA_PROVIDER, 4)}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {ns}
data:
  dependability.json: |
{block(dash, 4)}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {ns}
  labels: {{app: grafana, tier: monitoring}}
spec:
  replicas: 1
  selector:
    matchLabels: {{app: grafana}}
  template:
    metadata:
      labels: {{app: grafana, tier: monitoring}}
    spec:
      securityContext: {{fsGroup: 472}}
      containers:
        - name: grafana
          image: {GRAFANA_IMAGE}
          env:
            - {{name: GF_AUTH_ANONYMOUS_ENABLED, value: "true"}}
            - {{name: GF_AUTH_ANONYMOUS_ORG_ROLE, value: Admin}}
            - {{name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH, value: /etc/grafana/dashboards/dependability.json}}
          ports: [{{containerPort: 3000}}]
          readinessProbe:
            httpGet: {{path: /api/health, port: 3000}}
            periodSeconds: 5
          livenessProbe:
            httpGet: {{path: /api/health, port: 3000}}
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests: {{cpu: 100m, memory: 256Mi}}
            limits: {{cpu: "1", memory: 1Gi}}
          volumeMounts:
            - {{name: provisioning, mountPath: /etc/grafana/provisioning}}
            - {{name: dashboards, mountPath: /etc/grafana/dashboards}}
            - {{name: storage, mountPath: /var/lib/grafana}}
      volumes:
        - name: provisioning
          configMap:
            name: grafana-provisioning
            items:
              - {{key: datasource.yml, path: datasources/prometheus.yml}}
              - {{key: dashboards.yml, path: dashboards/university-is.yml}}
        - name: dashboards
          configMap: {{name: grafana-dashboards}}
        - name: storage
          emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {ns}
spec:
  type: NodePort
  selector: {{app: grafana}}
  ports: [{{port: 3000, targetPort: 3000, nodePort: {NODEPORT["grafana"]}}}]
"""


def kind_overlay():
    """Local 3-node cluster (1 control plane + 2 workers = nodes A and B) for the Kubernetes demo."""
    K = os.path.join(D, "kind")
    mount = "    extraMounts: [{hostPath: /tmp/univ-shared, containerPath: /shared}]   # stands in for an NFS share\n"
    ports = "".join(f"      - {{containerPort: {p}, hostPort: {p}}}   # {n}\n" for n, p in NODEPORT.items())
    write(os.path.join(K, "kind-cluster.yaml"),
          "# kind create cluster --name univ --config deploy/kind/kind-cluster.yaml   (generated by deploy/generate.py)\n"
          "kind: Cluster\napiVersion: kind.x-k8s.io/v1alpha4\nnodes:\n"
          "  - role: control-plane              # also hosts monitoring, so it survives a worker failure\n"
          + mount + "    extraPortMappings:                # NodePorts reachable on localhost\n" + ports
          + "  - role: worker                     # node A\n" + mount
          + "  - role: worker                     # node B\n" + mount)
    write(os.path.join(K, "shared-pv.yaml"),
          "# ReadWriteMany volume shared by every node (same Docker-host directory mounted into all kind nodes)\n"
          "apiVersion: v1\nkind: PersistentVolume\nmetadata:\n  name: univ-shared\nspec:\n  capacity: {storage: 1Gi}\n"
          "  accessModes: [ReadWriteMany]\n  persistentVolumeReclaimPolicy: Retain\n  storageClassName: shared\n"
          "  hostPath: {path: /shared, type: DirectoryOrCreate}\n")
    pin = """      - op: add
        path: /spec/template/spec/nodeSelector
        value: {node-role.kubernetes.io/control-plane: ""}
      - op: add
        path: /spec/template/spec/tolerations
        value: [{key: node-role.kubernetes.io/control-plane, operator: Exists, effect: NoSchedule}]
"""
    write(os.path.join(K, "kustomization.yaml"),
          "# kubectl apply -k deploy/kind     (generated by deploy/generate.py)\n"
          "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n  - ../k8s\n  - shared-pv.yaml\n"
          "patches:\n"
          "  - target: {kind: PersistentVolumeClaim, name: data}     # bind to the shared hostPath volume\n"
          "    patch: |-\n      - op: add\n        path: /spec/storageClassName\n        value: shared\n"
          "  - target: {kind: Deployment, labelSelector: tier=monitoring}   # monitoring on the control plane\n"
          "    patch: |-\n" + pin.rstrip("\n") + "\n"
          "  - target: {kind: StatefulSet, name: monitor}            # health monitor too, so it can report the failure\n"
          "    patch: |-\n" + pin)


def main():
    inst = compose("ft")
    compose("baseline")
    monitoring(inst)
    k8s(inst)
    kind_overlay()
    print("generated: docker-compose.yml, docker-compose.baseline.yml, deploy/k8s/*, deploy/kind/*, deploy/monitoring/*")


if __name__ == "__main__":
    main()
